EOD 1/18/17
Currently broken due to
File "./construct_tf_idf.py", line 154, in <module>
    idf_value = float(idf_line_pieces[6])
ValueError: invalid literal for float()

weird, there should be no comma separated lists in idf_file